### PR TITLE
Android styling and products bug fixes

### LINKED ISSUE #66: Styling bugs and inconsistencies on Android
* The map view is buggy and sometimes map markers randomly jump around (see videos and screenshots on #56).
* Sometimes the font on buttons and text fields becomes the default system font.
* Drop shadows don't work at all.

### LINKED ISSUE #77: Can't navigate to Products List or Product Details on Android
Tapping `See all __` on the map screen to see all products for a given store doesn't do anything, but also doesn't error. The same thing happens for the product cards. 

https://www.loom.com/share/5da95bda2f3640ccbc5cfb25c08403e1

### PR DESCRIPTION
**Pull request by wangannie**
[//]: # "These comments are meant for your reference. They are invisible and don't need to be deleted!"

# What's new in this PR
* Fixed styling inconsistencies on Android which resolves #66 including:
  * Fixed font inconsistencies(some buttons and text fields would switch to Roboto)
  * Fixed drop shadows (wouldn't show on Android)
* Fixed various Android-specific bugs like how the rewards button on the map screen was getting covered by the bottom sheet.
* Fixed Android-specific bugs with unresponsive touch gestures on the bottom sheet which resolves #77 so that:
  * Buttons linking to Products List and Product Details should work now
  * Horizontal scroll in products should work

FYI: Some gesture-related components must be imported from `react-native-gesture-handler` instead of `react-native` for them to work on Android. This fixed `FlatList` scrolling issues, but in some cases like for `TouchableOpacity`, `react-native-gesture-handler` worked for Android but wouldn't work for iOS.

[//]: # "Describe what's new in this PR in a few lines. A description and bullet points for specifics will suffice."

### Online sources
[//]: # "Optional - copy links to any tutorial or documentation that was useful to you when working on this PR"
**Styling:** 
Basically, I realized you can't use a custom font-weight or Android will get confused and resort to the system default. Also, regular shadows don't work on Android and you have to use elevation values.
https://github.com/react-navigation/react-navigation/issues/2822

**Touch gesture bugs:**
https://github.com/osdnk/react-native-reanimated-bottom-sheet/issues/16
https://github.com/osdnk/react-native-reanimated-bottom-sheet/issues/19
https://github.com/osdnk/react-native-reanimated-bottom-sheet/issues/20

### Related PRs

[//]: # "Optional - related PRs you're waiting on/ PRs that will conflict, etc; if this is a refactor, feel free to add PRs that previously modified this code"

## How to review
[//]: # "The order in which to review files and what to expect when testing locally"
**To test without running the repo locally: https://exp.host/@wangannie/healthycorners**
* Test on Android and see if it matches iOS/Figma.
* Look out for spots where it pulls the system default font.
* See if the map is jittery on a real Android device. I suspect it's just an issue with the simulator right now,  and I couldn't find any particular issues with our MapView setup.

## Next steps

[//]: # "What's NOT in this PR, doesn't work yet, and/or still needs to be done"
* Figure out drop shadow for the bottom sheet. We achieved this using an offset box-shadow on the bottom sheet content container, but since Android seems limited to elevation and doesn't allow for offsets, I couldn't figure out a workaround.

## Tests Performed, Edge Cases

[//]: # "Hopefully we will add a testing suite/CI soon, but until then note down the steps you took to test locally"

### Screenshots
* Fixed fonts in drawer:  Screenshot_1586324752

* Added shadows and fixed hidden Rewards button issue
Screenshot_1586324871
 * Products bug fix
https://www.loom.com/share/804797c171c04695b77ccf99a61bb546

### CODE REVIEW

File: screens/map/MapScreen.js [hunk 1]
```diff
@@ -252,7 +252,7 @@ export default class MapScreen extends React.Component {
             enabledInnerScrolling={false}
             enabledBottomClamp
             overdragResistanceFactor={1}
-            enabledGestureInteraction
+            enabledContentTapInteraction={false}
```
Comment (wangannie) [inline screens/map/MapScreen.js:255]: Honestly, I don't understand why this has to be false for the buttons to be clickable. It seems super counterintuitive but it finally worked.
