### PR TITLE
Fixed keyboard covering on Log In and Sign Up

### LINKED ISSUE #63: Fix keyboard covering issues on Login and Signup
Replace the temporary fix of shrunken spacing on login and signup from #56 with keyboardAvoidingView or some long-term solution. With the current spacing, it can still be blocked by the keyboard (iPhone 8 on the left)

image

### PR DESCRIPTION
**Pull request by wangannie**
[//]: # "These comments are meant for your reference. They are invisible and don't need to be deleted!"

# What's new in this PR
* Resolves #63 where the keyboard covered the text fields and buttons on smaller screens.
* Added Keyboard Avoiding to new auth screens from #97 

Note: I was originally using a regular `KeyboardAvoidingView` for `AuthScreenContainer` but I was having issues where the content would end up overlapping since it just adjusted with `flex: 1` and refused to go off the screen. I decided to switch to wrapping everything in a `ScrollView` inside `KeyboardAvoidingView` so the spacing wouldn't have to be adjusted based on screen size, and it makes sure that all of the screen content can always be accessible. Unfortunately, this sacrifices the smoothness of a pure `KeyboardAvoidingView`, but is probably the best solution for accessibility across different types of devices.

5/5 Update: Turned all the repeated `ScrollView`s into `AuthScrollContainer` with all the needed attributes.

## How to review
* Go through the login and signup flows and see if the behavior is intuitive. You should be able to:
  * Tap a text field/button without having to dismiss the keyboard
  * Moving away from the first text field in both LogIn and SignUp should automatically scroll you to the bottom so the button should be visible.
  * You should always be able to scroll up to hit the back button
  * On larger devices where all of the screen content is visible, there shouldn't be any visible auto-scrolling behavior and everything should look/work like it used to.

* I was having issues with my emulator, so this still needs to be tested on Android @12aschen Use [this expo link ](https://exp.host/@wangannie/healthy-corners-rewards-androidtestkeyboard)to test on Android.

### Online sources
Shoutout to @averyyip and https://github.com/calblueprint/1951coffee/pull/13 for the inspiration in 1951 to do a `ScrollView` within a `KeyboardAvoidingView` I still thought their interaction was rather jank, so I added the automatic scrolling to the bottom to make sure the proper fields will show.

### Related PRs
Originally began updating this in #97 but decided to split it up into a separate PR.

## Next steps
n/a

### Screenshots
https://www.loom.com/share/0f09f45e55fa41d1b1ee4ddb0efa739f

Behavior in new auth screens
https://www.loom.com/share/b70aed83bbfa47d591553e111b51c57f

CC: @anniero98 

[//]: # 'This tags in both Annies as a default. Feel free to change, or add on anyone who you should be in on the conversation.'

### CODE REVIEW

File: screens/auth/LogInScreen.js [hunk 1]
```diff
@@ -160,55 +160,66 @@ export default class LogInScreen extends React.Component {
...
-          </FilledButtonContainer>
-
-          {/* TODO @tommypoa: Forgot password functionality
+        <ScrollView
+          ref={(ref) => {
+            this.scrollView = ref;
+          }}
+          style={{ flex: 1 }}
+          keyboardShouldPersistTaps="always"
+          showsVerticalScrollIndicator={false}>
```
Comment (kennethlien) [inline screens/auth/LogInScreen.js:169]: idk what this is but i assume it's doing the magic thing, you're an absolute legend

File: screens/auth/SignUpScreen.js [hunk 2]
```diff
@@ -300,21 +306,22 @@ export default class SignUpScreen extends React.Component {
...
 
             <AuthTextField
               fieldType="Phone Number"
               value={this.state.values[signUpFields.PHONENUM]}
-              onBlurCallback={(value) =>
-                this.updateError(value, signUpFields.PHONENUM)
-              }
+              onBlurCallback={(value) => {
+                this.updateError(value, signUpFields.PHONENUM);
+              }}
```
Comment (tommypoa) [inline screens/auth/SignUpScreen.js:324]: If for some reason the user scrolls up while typing the phone number, perhaps to change their name (such that the sign up button is hidden but the password field is not hidden), tapping on the password field does not animate to show the sign up button – maybe add the blur callback to the phone number field too? Definitely an edge case though

Comment (wangannie) [reply screens/auth/SignUpScreen.js]: Yes nice catch! I added it to both fields now.
