### PR TITLE
Fixed accepted program description wrap issue

### LINKED ISSUE #135: Store details scrolling is cut off on smaller devices
Originally discovered by @12aschen
image

### PR DESCRIPTION
**Pull request by thumn**
[//]: # "These comments are meant for your reference. They are invisible and don't need to be deleted!"

# What's new in this PR
- Store program descriptions now wrap as expected in the store details screen
- Refactored accepted programs section into separate reusable components
- Changed copy for SNAP Match program description
- Added external link to DCCK's 5-for-5 program website
- Fixed #135 store details scrolling issues

[//]: # "Describe what's new in this PR in a few lines. A description and bullet points for specifics will suffice."

## How to review
Navigate to the store details screen for various stores and verify that the text is wrapping correctly and that everything looks clean.
Notable stores: Grubb's (has SNAP Match, EBT, WIC) and Nam's (has Healthy Rewards)

[//]: # 'The order in which to review files and what to expect when testing locally'

### Online sources

[//]: # 'Optional - copy links to any tutorial or documentation that was useful to you when working on this PR'

### Related PRs
#98 

[//]: # "Optional - related PRs you're waiting on/ PRs that will conflict, etc; if this is a refactor, feel free to add PRs that previously modified this code"

## Next steps
Store details screen is pretty much done after this, I think!
NOTE: Vertical text alignment in chips might be a hard issue to fix and probably won't be a priority given how much time we have left. It also doesn't really affect readability or accessibility. On some phones like mine, the bug might not show up, so maybe we can backlog it?

[//]: # "What's NOT in this PR, doesn't work yet, and/or still needs to be done"

### Screenshots
IMG_F8186CE8FE85-1

[//]: # "Add screenshots of expected behavior - GIFs if you're feeling fancy!"

CC: @anniero98 @wangannie

[//]: # 'This tags in both Annies as a default. Feel free to change, or add on anyone who you should be in on the conversation.'

### CODE REVIEW

File: screens/map/StoreDetailsScreen.js [hunk 1]
```diff
@@ -3,7 +3,6 @@ import { Linking } from 'expo';
 import PropTypes from 'prop-types';
 import React from 'react';
 import { ScrollView, TouchableOpacity, View } from 'react-native';
-import { Chip } from 'react-native-paper';
```
Comment (kennethlien) [inline screens/map/StoreDetailsScreen.js:6]: goodbye chippy :')

Comment (thumn) [reply screens/map/StoreDetailsScreen.js:6]: it's ok he just moved files : ' ) he's in a better place now :'   )
