### PR TITLE
MapScreen Bug Fixes

### LINKED ISSUE #105: [Styling] Store names overlap when you zoom out
The store names are super cluttered when you zoom out (maybe have the names disappear at a certain zoom out point?):

IMG_7826

### LINKED ISSUE #109: UI nitpick: Can't see your exact current location on map
IMG_4441

### LINKED ISSUE #126: Inconsistent Current Location indicator sizing
* Originally mentioned by Gaby on iPhone 6
image

### PR DESCRIPTION
**Pull request by tommypoa**
[//]: # "These comments are meant for your reference. They are invisible and don't need to be deleted!"

# What's new in this PR

[//]: # "Describe what's new in this PR in a few lines. A description and bullet points for specifics will suffice."
- Resolves #105 by hiding store name when zoomed out to a certain level
- Store zooms to top-half of screen
- Current location icon size is constant across all screens (Resolves #126 bug: Extra large current location for smaller screen phones)
- Text border/outline for store names
   - Currently has a primary orange color because lighter colors/white does not work 😯
- Resolves #109: Recenter location does not render if
   - There are errors with location fetching (including user disallowing location services)
   - User is too far away

## Relevant Links

[//]: # "Optional - related PRs you're waiting on/ PRs that will conflict, etc; if this is a refactor, feel free to add PRs that previously modified this code"
- NIL

## How to review

[//]: # "The order in which to review files and what to expect when testing locally"
- Test all new features
   - Location known and unknown situation and whether current location icon is there
   - Check if current location icon of different phone screens is ok
## Next steps

[//]: # "What's NOT in this PR, doesn't work yet, and/or still needs to be done"
- Enabling map rotation #81 

## Tests Performed, Edge Cases

[//]: # "Hopefully we will add a testing suite/CI soon, but until then note down the steps you took to test locally"

### Screenshots

[//]: # "Add screenshots of expected behavior - GIFs if you're feeling fancy!"
- Hidden store names when zoomed out
image

- Recenter location button does not show (+ showing default store), featuring the orange text outline 🥵
image
- Selected store zooms into top half of screen
image

CC: @wangannie

[//]: # "This tags in both Annies as a default. Feel free to change, or add on anyone who you should be in on the conversation."

### CODE REVIEW

File: styled/store.js [hunk 1]
```diff
@@ -15,6 +15,8 @@ export const MarkerStoreName = styled.Text`
   line-height: ${props => (props.focused ? '24px' : '20px')};
   text-align: center
   color: ${Colors.activeText};
+  text-shadow-color: ${Colors.primaryOrange}
```
Comment (thumn) [inline styled/store.js:18]: nit: semicolon?
